<?php 
/**
 * Widgets: sidebar
 */
 

$hiddenMenuID = Bigace_Config::get("envision", "hidden.menu");
$hiddenMenu = null;
if ($hiddenMenuID !== null) {
    $hiddenMenu = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, $hiddenMenuID, $this->MENU->getLanguageID());
}
 
$this->t()->load('bigace');
$topLevel = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, _BIGACE_TOP_LEVEL, $this->MENU->getLanguageID());
if($topLevel === null)
    $topLevel = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, _BIGACE_TOP_LEVEL);
$allLinks = $this->tplLinks($this->MENU, $this->USER);
$layout = $this->directory().'envision/';


?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<?php echo $this->headStyle(); ?>
<?php echo $this->headLink(); ?>

<?php echo $this->headMeta(); ?>

<?php echo $this->metatags($this->MENU); ?>

<?php echo $this->headScript(); ?>

<link rel="stylesheet" href="<?php echo $layout; ?>images/Envision.css" type="text/css" />

<title>Envision</title>
	
</head>

<body>
<!-- wrap starts here -->
<div id="wrap">
		
		<!--header -->
		<div id="header">			
				
			<h1 id="logo-text"><a href="<?php echo $this->link($this->topLevel);?>"><?php echo $this->sitename();?></a></h1>		
			<p id="slogan">put your site slogan here...</p>		
			
			<div id="header-links">
			
			<p>
				<a href="index.html">Home</a> | 
				<a href="index.html">Contact</a> | 
				<a href="index.html">Site Map</a>			
			</p>		
		</div>		
						
		</div>
		
		<!-- menu -->	
		<div  id="menu">
			<ul>
				<?php 
            echo '<li><a href="'.$this->link($topLevel).'"';
            if($this->MENU->getID() == 
                $topLevel->getID())
                echo ' class="current"';
            echo '>'.$topLevel->getName().'</a></li>';

            echo $this->menu(
                $topLevel, 
                array(
                    'prefix' => '<li>', 
                    'suffix' => '</li>', 
                    'selected' => 'current', 
                    'select' => $this->MENU, 
                    
                )
            );

        ?>	
			</ul>
		</div>					
			
		<!-- content-wrap starts here -->
		<div id="content-wrap">
				
			<div id="sidebar">
			
				<h3><?php echo $this->t('search');?></h3>	
				<form action="<?php echo $allLinks['search']; ?>" class="searchform" method="post">
					<p>
					<input name="search" class="textbox" type="text" />
  					<input name="searchsubmit" class="button" value="<?php echo $this->t('search_button'); ?>" type="submit" />
					</p>			
				</form>	
					
				<h3>Sidebar Menu</h3>
				<ul class="sidemenu">				
					<?php 
              $widgets = $this->widgets($this->MENU);
              foreach($widgets as $widget) {
                echo '<h3>' . $widget->getTitle() . '</h3>';
                echo $widget->getHtml();
              }
            ?>
				</ul>
				
			
				<h3>Links</h3>
				<ul class="sidemenu">
					<li><a href="http://www.pdphoto.org/">PDPhoto.org</a></li>
					<li><a href="http://www.squidfingers.com/patterns/">Squidfingers</a></li>
					<li><a href="http://www.alistapart.com">Alistapart</a></li>					
				   	<li><a href="http://www.cssmania.com/">CSS Mania</a></li>
				</ul>
			
				<h3>Sponsors</h3>
                <ul class="sidemenu">
                    <li><a href="http://www.dreamtemplate.com" title="Website Templates">
                    <strong>DreamTemplate</strong></a> <br /> Over 6,000+ Premium Web Templates</li>
                    <li><a href="http://www.themelayouts.com" title="WordPress Themes">
                    <strong>ThemeLayouts</strong></a> <br /> Premium WordPress &amp; Joomla Themes</li>
                    <li><a href="http://www.imhosted.com" title="Website Hosting">
                    <strong>ImHosted.com</strong></a> <br /> Affordable Web Hosting Provider</li>
                    <li><a href="http://www.dreamstock.com" title="Stock Photos">
                    <strong>Dreamstock</strong></a> <br /> Download Amazing Stock Photos</li>
                    <li><a href="http://www.evrsoft.com" title="Website Builder">
                    <strong>Evrsoft</strong></a> <br /> Website Builder Software &amp; Tools</li>
                    <li><a href="http://www.webhostingwp.com" title="Web Hosting">
                    <strong>Web Hosting</strong></a> <br /> Top 10 Hosting Reviews</li>
                </ul>
				
				<h3>Wise Words</h3>
				<div class="left-box">
					<p>&quot;Evaluation of the past is the first step toward 
					vision for the future.&quot; </p>
					
					<p class="align-right">- Chris Widener</p>
				</div>	
				
				<h3>Support Styleshout</h3>
				<div class="left-box">
					<p>If you are interested in supporting my work and would like to contribute, you are
					welcome to make a small donation through the 
					<a href="http://www.styleshout.com/">donate link</a> on my website - it will 
					be a great help and will surely be appreciated.</p>
				</div>							
								
			</div>
				
			<div id="main">
				
				<?php
                echo $this->content();
            ?>

			</div>
		
		<!-- content-wrap ends here -->	
		</div>
					
		<!--footer starts here-->
		<div id="footer">
			
            <p>
		    &copy; Copyright <?php echo date('Y', time()); ?>
        <?php echo Bigace_Config::get("community", "copyright.holder", "BIGACE CMS"); ?>.

            &nbsp;&nbsp;&nbsp;&nbsp;

		    Template by <a href="http://www.styleshout.com/">styleshout</a>
            
            &nbsp;&nbsp;&nbsp;&nbsp;

		   <?php 
            echo '<a href="'.$this->link($topLevel).'">'.$topLevel->getName().'</a>';
            
		    if ($hiddenMenu !== null) {
		        echo $this->menu(
                    $hiddenMenu, 
                    array(
                        'prefix' => ' | ', 
                        'suffix' => '',                                        
                    )
                );
	   	    } 
   	    ?>
   	    </p>
				
		</div>	

<!-- wrap ends here -->
</div>

</body>
</html>
