<?php
/**
 * Widgets: sidebar
 */


$hiddenMenuID = Bigace_Config::get("azulmedia", "hidden.menu");
$hiddenMenu = null;
if ($hiddenMenuID !== null) {
    $hiddenMenu = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, $hiddenMenuID, $this->MENU->getLanguageID());
}

$this->t()->load('bigace');
$topLevel = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, _BIGACE_TOP_LEVEL, $this->MENU->getLanguageID());
if($topLevel === null)
    $topLevel = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, _BIGACE_TOP_LEVEL);
$allLinks = $this->tplLinks($this->MENU, $this->USER);
$layout = $this->directory().'azulmedia/';

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>

<title>Azulmedia</title>

<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />
<?php echo $this->headStyle(); ?>
<?php echo $this->headLink(); ?>

<?php echo $this->headMeta(); ?>

<?php echo $this->metatags($this->MENU); ?>

<?php echo $this->headScript(); ?>

<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $layout; ?>images/Azulmedia.css" />

</head>

<body>
<!-- wrap starts here -->
<div id="wrap">

        <div id="header">

                <h1 id="logo"><a href="<?php echo $this->link($this->topLevel);?>"><?php echo $this->sitename();?></a></h1>


                <!-- Menu Tabs -->
                <div id="menu">
                        <ul>
                        <?php
                                  echo '<li><a href="'.$this->link($topLevel).'"';
                                         if($this->MENU->getID() ==
                                         $topLevel->getID())
                                         echo ' class="current"';
                                         echo '>'.$topLevel->getName().'</a></li>';

                                         echo $this->menu(
                                        $topLevel,
                                        array(
                                            'prefix' => '<li>',
                                            'suffix' => '</li>',
                                            'selected' => 'current',
                                            'select' => $this->MENU,

                                        )
                                    );

                                ?>
                        </ul>
                </div>

        </div>

        <!-- content-wrap starts here -->
        <div id="content-wrap">

                <div id="main">


                        <div class="box">
                        <?php
$breadcrumbs = $this->wayHome($this->MENU, true);
$amount = count($breadcrumbs);

if($amount > 0)
{
    ?>
    <ul id="breadcrumbs">
    <?php
        $i = 0;
        foreach ($breadcrumbs as $id => $item) {
                echo '&raquo;<li';
                if($i == 0) echo ' class="first"';
                if($i == $amount-1) echo ' class="last"';
                echo '><a href="'.$this->link($item).'">'.$item->getName().'</a></li> ';
                $i++;
        }
    ?>
    </ul>
    <?php
}
?>



                                <?php
            echo $this->content();
             ?>

                        </div>

                </div>

        <div id="sidebar" >
                      <h2><?php echo $this->t('search'); ?></h2>
                     <div class="searchform">
                                <form action="<?php echo $allLinks['search']; ?>" method="post">
                                        <p>
                                        <input name="search" class="textbox" type="text" />
                                        <input type="hidden" name="language" value="<?php echo $this->MENU->getLanguageID(); ?>" />
                                          <input name="search" class="button" value="<?php echo $this->t('search'); ?>" type="submit" />
                                        </p>
                                </form>
                      </div>

                      <div id="widgets">

                                <?php
                                            $widgets = $this->widgets($this->MENU);
                                            foreach($widgets as $widget) {
                                              echo '<h2>' . $widget->getTitle() . '</h2>';
                                              echo '<ul class="sidemenu">';
                                              echo $widget->getHtml();
                                              echo '</ul>';
                                            }
                                          ?>
                      </div>
                </div>

        <br />
    <div class="clear"></div>
        <!-- content-wrap ends here -->
        </div>

<!-- wrap ends here -->
</div>

<!-- footer starts here -->
<div id="footer-wrap">

        <div class="footer-left">
                <p class="align-left">
                &copy; Copyright <?php echo date('Y', time()); ?>
        <a href="http://www.bigace.de">BIGACE CMS</a> |
                Template by <a href="http://www.styleshout.com/">styleshout</a>
               </p>
        </div>

        <div class="footer-right">
                <p class="align-right">
                <?php
            echo '<a href="'.$this->link($topLevel).'">'.$topLevel->getName().'</a>';

                    if ($hiddenMenu !== null) {
                        echo $this->menu(
                    $hiddenMenu,
                    array(
                        'prefix' => ' | ',
                        'suffix' => '',
                    )
                );
                       }
               ?>
                </p>
        </div>

</div>
<!-- footer ends here -->

</body>
</html>