<?php
/* @license http://opensource.org/licenses/gpl-license.php GNU Public License
   @author Kevin Papst
   @copyright Copyright (C) Kevin Papst
   @version $Id: edit.phtml 190 2011-04-04 14:40:02Z kevin $ */

if (isset($this->ERROR)) {
    echo $this->message($this->ERROR, 'error');
}

if (isset($this->INFO)) {
    echo $this->message($this->INFO, 'info');
}

echo $this->backlink($this->BACK_URL);

?>

<form action="<?php echo $this->SAVE_URL; ?>" method="post">
<input type="hidden" name="template" value="<?php echo $this->TEMPLATE_NAME; ?>">

<table border="0" width="100%" cellspacing="0" cellpadding="0">
<tr>
	<td width="150">
	  <?php echo $this->t('name'); ?>
	</td>
    <td>
         <?php echo $this->NAME; ?>
		 / <?php echo $this->FILENAME; ?>
    </td>
</tr>
<tr>
	<td>
        <?php echo $this->t('description'); ?>
	</td>
    <td>
		<?php echo $this->formText("description", $this->TEMPLATE_DESCRIPTION); ?>
    </td>
</tr>
<tr>
    <td colspan="2">
    </td>
</tr>
<tr>
    <td>
        <?php echo $this->t('state'); ?>
    </td>
    <td>
        <label><input type="checkbox" name="isinclude" value="1" <?php echo $this->IS_INCLUDE_CHECKED; ?> id="is_include"> <?php echo $this->t('file_is_include'); ?></label>

        <label><input type="radio" name="inwork" value="1" <?php echo $this->INWORK_TRUE_CHECKED; ?> id="inworkTrue" /> <?php echo $this->t('in_work_true'); ?></label>
        <label><input type="radio" name="inwork" value="0" <?php echo $this->INWORK_FALSE_CHECKED; ?> id="inworkFalse" /> <?php echo $this->t('in_work_false'); ?></label>
    </td>
</tr>
</table>

<?php echo $this->codeEditor('tplcontent', $this->TEMPLATE_CONTENT); ?>

<?php echo $this->saveButton('updateTpl'); ?>

</form>
