<?php
/* 	@license http://opensource.org/licenses/gpl-license.php GNU Public License
	@author Kevin Papst 
	@copyright Copyright (C) Kevin Papst 
	@version $Id: unconfigured.phtml 4 2010-07-17 14:20:17Z kevin $ */

echo '<b>'.$this->t('error_unconfigured').'</b>';

echo '<ul>';
foreach($this->MISSING as $m)
    echo '<li>'.$m.'</li>';
echo '</ul>';

echo '<a href="'.$this->CONFIG_URL.'">'.$this->t('news_header_config').'</a>';
