<?php
/**
 * Widgets: sidebar
 */


$hiddenMenuID = Bigace_Config::get("sandstone", "hidden.menu");
$hiddenMenu = null;
if ($hiddenMenuID !== null) {
    $hiddenMenu = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, $hiddenMenuID, $this->MENU->getLanguageID());
}

$this->t()->load('bigace');
$topLevel = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, _BIGACE_TOP_LEVEL, $this->MENU->getLanguageID());
if($topLevel === null)
    $topLevel = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, _BIGACE_TOP_LEVEL);
$allLinks = $this->tplLinks($this->MENU, $this->USER);
$layout = $this->directory().'sandstone/';

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Title      : Sandstone
Version    : 1.0
Released   : 20091109
Description: A two-column fixed-width template suitable for small websites.

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Sandstone by Free Css Templates</title>

<?php echo $this->headStyle(); ?>
<?php echo $this->headLink(); ?>

<?php echo $this->headMeta(); ?>

<?php echo $this->metatags($this->MENU); ?>

<?php echo $this->headScript(); ?>

<link href="<?php echo $layout; ?>default.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="wrapper">
  <div id="header">
    <div id="logo">
      <h1><a href="<?php echo $this->link($this->topLevel);?>"><?php echo $this->sitename();?></a></h1>
    </div>
    <!-- end div#logo -->
  </div>
  <!-- end div#header -->
  <div id="menu">
    <ul>
      <?php
            echo '<li><a href="'.$this->link($topLevel).'"';
            if($this->MENU->getID() ==
                $topLevel->getID())
                echo ' class="current"';
            echo '>'.$topLevel->getName().'</a></li>';

            echo $this->menu(
                $topLevel,
                array(
                    'prefix' => '<li>',
                    'suffix' => '</li>',
                    'selected' => 'current',
                    'select' => $this->MENU,

                )
            );

        ?>
    </ul>
  </div>
  <div id="splash"><img src="<?php echo $layout; ?>images/img01.jpg" width="940" height="410" alt="" /></div>
  <!-- end div#menu -->
  <div id="page">
    <div id="page-bgtop">
      <div id="content">
      <?php
$breadcrumbs = $this->wayHome($this->MENU, true);
$amount = count($breadcrumbs);

if($amount > 0)
{
    ?>
    <ul id="breadcrumbs">
    <?php
        $i = 0;
        foreach ($breadcrumbs as $id => $item) {
                echo '&raquo;<li';
                if($i == 0) echo ' class="first"';
                if($i == $amount-1) echo ' class="last"';
                echo '><a href="'.$this->link($item).'">'.$item->getName().'</a></li> ';
                $i++;
        }
    ?>
    </ul>
    <?php
}
?>

       <?php
            echo $this->content();
             ?>

      </div>
      <!-- end div#content -->
      <div id="sidebar">

          <div id="search">
            <h2>Search</h2>
            <form method="post" action="<?php echo $allLinks['search']; ?>">
              <fieldset>
                <input type="text" id="search-text" name="search" value="" />
                <input type="hidden" name="language" value="<?php echo $this->MENU->getLanguageID(); ?>" />
                <input type="submit" id="search-submit" value="<?php echo $this->t('search'); ?>" />
              </fieldset>
            </form>
          </div>



              <?php
              $widgets = $this->widgets($this->MENU);
              foreach($widgets as $widget) {
                echo '<h2>' . $widget->getTitle() . '</h2>';
                echo $widget->getHtml();
              }
            ?>


      </div>
      <!-- end div#sidebar -->
      <div style="clear: both; height: 1px"></div>
    </div>
  </div>
  <!-- end div#page -->
  <div id="footer">
    <p>&copy; Copyright <?php echo date('Y', time()); ?>
        <a href="http://www.bigace.de">BIGACE CMS</a>. Template by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>. </p>
  </div>
  <!-- end div#footer -->
</div>
<!-- end div#wrapper -->
</body>
</html>