<?php
/**
 * Widgets: sidebar
 *
 * $Id: $
 */

$this->t()->load('bigace');
$this->adminBar()->includeJQuery(true)->enable();

$menu         = $this->MENU;
$hiddenMenuID = Bigace_Config::get("emplode", "hidden.menu");
$hiddenMenu   = null;
$topLevel     = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, _BIGACE_TOP_LEVEL, $menu->getLanguageID());
$allLinks     = $this->tplLinks($menu, $this->USER);
$layout       = $this->directory().'emplode/';
$breadcrumbs  = $this->wayHome($menu, true);

if ($hiddenMenuID !== null) {
    $hiddenMenu = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, $hiddenMenuID, $menu->getLanguageID());
}
if ($topLevel === null) {
    $topLevel = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, _BIGACE_TOP_LEVEL);
}

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <?php echo $this->headStyle(); ?>
    <?php echo $this->headLink(); ?>

    <?php echo $this->headMeta(); ?>

    <?php echo $this->metatags($menu); ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $layout; ?>style.css" media="screen" />
    <?php echo $this->headScript(); ?>

    <?php Bigace_Hooks::do_action('tpl_header', $menu); ?>
</head>
<body>
    <div id="header">
        <div class="center_wrapper">
            <div id="toplinks">
                <div id="toplinks_inner">
                    <?php
                        // load most important links that we will use within the template
                        $allLinks = $this->tplLinks($menu, $this->USER);

                        // nicht angemeldet
                        if (isset($allLinks['login'])) {
                            echo '<a target="_blank" href="'.$allLinks['login'].'">Login</a>';
                        }
                    ?>
                </div>
            </div>
            <div class="clearer">&nbsp;</div>
            <div id="site_title">
                <h1><a href="<?php echo $this->link($this->topLevel);?>"><?php echo $this->sitename();?></a></h1>
            </div>
        </div>
    </div>

    <div id="navigation">
        <div class="center_wrapper">
            <ul>
            <?php
                echo '<li><a href="'.$this->link($topLevel).'"';
                if($this->MENU->getID() == $topLevel->getID()) {
                    echo ' class="current"';
                }

                echo '>'.$topLevel->getName().'</a></li>';

                echo $this->menu(
                    $topLevel,
                    array(
                        'prefix'   => '<li>',
                        'suffix'   => '</li>',
                        'selected' => 'current',
                        'select'   => $menu,
                    )
                );
            ?>
            </ul>
            <div class="clearer">&nbsp;</div>
        </div>
        <?php
        // remove me, if you dont like the second level menu!
        if ($menu->getParentId() >= _BIGACE_TOP_LEVEL)
        {
            if ($menu->getParentId() == _BIGACE_TOP_LEVEL) {
                $parent = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, $menu->getId(), $menu->getLanguageID());
            } else {
                $parent = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, $menu->getParentId(), $menu->getLanguageID());
            }

            $subNavi = $this->menu(
                $parent,
                array(
                    'prefix'   => '<li>',
                    'suffix'   => '</li>',
                    'selected' => 'current',
                    'select'   => $menu,
                )
            );

            if (strlen($subNavi) > 0) {
                echo '<div class="center_wrapper"><ul class="subnavi">';
                echo $subNavi;
                echo '</ul><div class="clearer">&nbsp;</div></div>';
            }
        }
        ?>
    </div>

    <div id="main_wrapper_outer">
        <div id="main_wrapper_inner">
            <div class="center_wrapper">
                <div class="left" id="main">
                    <div id="main_content">
                    <?php
                    $amount = count($breadcrumbs);

                    if($amount > 0)
                    {
                        echo '<ul id="breadcrumbs">';
                        $i = 0;
                        foreach ($breadcrumbs as $id => $item) {
                            echo '&raquo;<li';
                            if($i == 0) echo ' class="first"';
                            if($i == $amount-1) echo ' class="last"';
                            echo '><a href="'.$this->link($item).'">'.$item->getName().'</a></li> ';
                            $i++;
                        }
                        echo '</ul>';
                    }

                    echo $this->content();
                    ?>
                    </div>
                </div>

                <div class="right" id="sidebar">
                    <div id="sidebar_content">
                        <div class="box_title"><?php echo $this->t('search');?></div>
                        <div class="box_content">
                            <form id="qsearch" action="<?php echo $allLinks['search']; ?>" method="post" >
                            <p>
                            <input class="tbox" type="text" name="search" value="" title="" size="25"/>
                            <input type="hidden" name="language" value="<?php echo $menu->getLanguageID(); ?>" />
                            <input class="btn" value="<?php echo $this->t('search'); ?>" alt="<?php echo $this->t('search');?>" type="submit"/>
                            </p>
                            </form>
                        </div>
                        <div class="box">
                            <?php
                            $widgets = $this->widgets($menu);
                            foreach($widgets as $widget) {
                                echo '<div class="box_title">' . $widget->getTitle() . '</div>';
                                echo $widget->getHtml();
                            }
                            ?>
                        </div>
                    </div>
                </div>
                <div class="clearer">&nbsp;</div>
            </div>
        </div>
    </div>

    <div id="footer">
        <div class="center_wrapper">
            <div class="left">
                &copy; Copyright <?php echo date('Y', time()); ?>
                <?php echo Bigace_Config::get("community", "copyright.holder", "BIGACE CMS"); ?>
            </div>
            <div class="right">
                <?php /* Please leave this link to spread the word for Bigace :) Thank you! */ ?>
                Powered by <?php echo $this->copyright(true); ?> |
                <a href="http://templates.arcsin.se/">Website template by Arcsin</a>
            </div>
            <div class="clearer">&nbsp;</div>
        </div>
    </div>
    <?php echo $this->adminBar(); ?>
</body>
</html>
