<?php
/**
 * Contents: footermiddle, footerright
 * Widgets: sidebar
 */


$hiddenMenuID = Bigace_Config::get("techjunkie", "hidden.menu");
$hiddenMenu = null;
if ($hiddenMenuID !== null) {
    $hiddenMenu = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, $hiddenMenuID, $this->MENU->getLanguageID());
}

$this->t()->load('bigace');
$topLevel = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, _BIGACE_TOP_LEVEL, $this->MENU->getLanguageID());
if($topLevel === null)
    $topLevel = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, _BIGACE_TOP_LEVEL);
$allLinks = $this->tplLinks($this->MENU, $this->USER);
$layout = $this->directory().'techjunkie/';


?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>

<title>TechJunkie</title>

<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
        <meta name="description" content=""/>
        <meta name="keywords" content="" />
        <meta name="author" content="" />

<link rel="stylesheet" href="<?php echo $layout; ?>images/TechJunkie.css" type="text/css" />

</head>

<body>
<!-- wrap starts here -->
<div id="wrap">

        <!--header -->
        <div id="header">

                <h1 id="logo-text"><a href="<?php echo $this->link($this->topLevel);?>" title=""><?php echo $this->sitename();?></a></h1>
                <p id="slogan"></p>

                <form id="quick-search" action="<?php echo $allLinks['search']; ?>" method="post">
                        <p>
                        <label for="qsearch">Search:</label>
                        <input class="tbox" id="qsearch" type="text" name="search" value="" title="" />
                        <input class="btn" alt="Search" type="image" name="searchsubmit" title="" src="<?php echo $layout; ?>images/search.gif" />
                        </p>
                </form>

        <!--header ends-->
        </div>

        <!-- navigation starts-->
        <div  id="nav">
                <ul>
                        <?php
            echo '<li><a href="'.$this->link($topLevel).'"';
            if($this->MENU->getID() ==
                $topLevel->getID())
                echo ' class="current"';
            echo '>'.$topLevel->getName().'</a></li>';

            echo $this->menu(
                $topLevel,
                array(
                    'prefix' => '<li>',
                    'suffix' => '</li>',
                    'selected' => 'current',
                    'select' => $this->MENU,

                )
            );

        ?>
                </ul>
        <!-- navigation ends-->
        </div>

        <!-- content-wrap starts -->
        <div id="content-wrap">

                <div id="main">
                <?php
$breadcrumbs = $this->wayHome($this->MENU, true);
$amount = count($breadcrumbs);

if($amount > 0)
{
    ?>
    <ul id="breadcrumbs">
    <?php
        $i = 0;
        foreach ($breadcrumbs as $id => $item) {
                echo '&raquo;<li';
                if($i == 0) echo ' class="first"';
                if($i == $amount-1) echo ' class="last"';
                echo '><a href="'.$this->link($item).'">'.$item->getName().'</a></li> ';
                $i++;
        }
    ?>
    </ul>
    <?php
}
?>
                        <?php
            echo $this->content();
                         ?>

                <!-- main ends -->
                </div>

                <div id="sidebar">
                   <?php
              $widgets = $this->widgets($this->MENU);
              foreach($widgets as $widget) {
                echo '<h3>' . $widget->getTitle() . '</h3>';
                echo $widget->getHtml();
                 }
                 ?>

                <!-- sidebar ends -->
                </div>

        <!-- content-wrap ends-->
        </div>

        <!-- footer starts -->
        <div id="footer-wrap"><div id="footer-content">

                <div id="footer-columns">
                        <div class="col3">
                        <h3><?php echo $this->t('admin');?></h3>
                                <ul>
                                <?php
// load most important links that we will use within the template
$allLinks = $this->tplLinks($this->MENU, $this->USER);

    if (isset($allLinks['login'])) {
    // nicht angemeldet
    echo '<li><a target="_blank" href="'.$allLinks['login'].'">Login</a></li>';
    ?>



            <?php
        } else {
            if (isset($allLinks['admin'])) {
                echo '<li><a target="_blank" href="'.$allLinks['admin'].'">Administration </a></li>';
        }
            if (isset($allLinks['editor'])) {
                echo '<li><a target="_blank" href="'.$allLinks['editor'].'">Edit </a></li>';
        }
            if (isset($allLinks['logout'])) {
              echo '<li><a href="'.$allLinks['logout'].'">Logout</a></li>';
     }
    }

    ?>
                         </ul>
                        </div>

                        <div class="col3-center">
                        <?php
            echo $this->content('footermiddle');
                         ?>
                        </div>

                        <div class="col3">
                        <?php
            echo $this->content('footerright');
                         ?>
                        </div>
                <!-- footer-columns ends -->
                </div>

                <div id="footer-bottom">
                        <p>
                        &copy; Copyright <?php echo date('Y', time()); ?>
                        <a href="http://www.bigace.de">BIGACE CMS</a> |
                        Design by: <a href="http://www.styleshout.com/">styleshout</a>
                        </p>
                </div>

<!-- footer ends-->
</div></div>

<!-- wrap ends here -->
</div>

</body>
</html>