<?php
/**
 * Widgets: sidebar
 */


$hiddenMenuID = Bigace_Config::get("simpleblog", "hidden.menu");
$hiddenMenu = null;
if ($hiddenMenuID !== null) {
    $hiddenMenu = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, $hiddenMenuID, $this->MENU->getLanguageID());
}

$this->t()->load('bigace');
$topLevel = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, _BIGACE_TOP_LEVEL, $this->MENU->getLanguageID());
if($topLevel === null)
    $topLevel = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, _BIGACE_TOP_LEVEL);
$allLinks = $this->tplLinks($this->MENU, $this->USER);
$layout = $this->directory().'simpleblog/';

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>

<title>SimpleBlog</title>

<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />
<?php echo $this->headStyle(); ?>
<?php echo $this->headLink(); ?>

<?php echo $this->headMeta(); ?>

<?php echo $this->metatags($this->MENU); ?>

<?php echo $this->headScript(); ?>

<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $layout; ?>images/SimpleBlog.css" />

</head>

<body>
<!-- Wrap -->
<div id="wrap">

                <!-- Header -->
                <div id="header">

                        <h1 id="logo"><a  id="slogan" href="<?php echo $this->link($this->topLevel);?>" ><?php echo $this->sitename();?></a></h1>
                        <h2 id="slogan"></h2>

                        <div id="searchform">
                                <form method="post" class="search" action="<?php echo $allLinks['search']; ?>" >
                                        <p><input name="search" class="textbox" type="text" />
                                         <input type="hidden" name="language" value="<?php echo $this->MENU->getLanguageID(); ?>" />
                                          <input name="search" class="button" type="submit" value="<?php echo $this->t('search'); ?>" /></p>
                                </form>
                        </div>

                </div>

                <!-- menu -->
                <div id="menu">
                        <ul>
                                <?php
                                  echo '<li><a href="'.$this->link($topLevel).'"';
                                         if($this->MENU->getID() ==
                                         $topLevel->getID())
                                         echo ' class="current"';
                                         echo '>'.$topLevel->getName().'</a></li>';

                                         echo $this->menu(
                                        $topLevel,
                                        array(
                                            'prefix' => '<li>',
                                            'suffix' => '</li>',
                                            'selected' => 'current',
                                            'select' => $this->MENU,

                                        )
                                    );

                                ?>
                        </ul>
                </div>


                <!--Content Wrap -->
                <div id="content-wrap">

                        <div id="main">
                        <?php
$breadcrumbs = $this->wayHome($this->MENU, true);
$amount = count($breadcrumbs);

if($amount > 0)
{
    ?>
    <ul id="breadcrumbs">
    <?php
        $i = 0;
        foreach ($breadcrumbs as $id => $item) {
                echo '&raquo;<li';
                if($i == 0) echo ' class="first"';
                if($i == $amount-1) echo ' class="last"';
                echo '><a href="'.$this->link($item).'">'.$item->getName().'</a></li> ';
                $i++;
        }
    ?>
    </ul>
    <?php
}
?>

                         <?php
            echo $this->content();
             ?>

                        </div>

            <div id="sidebar">



                                         <?php
                                            $widgets = $this->widgets($this->MENU);
                                            foreach($widgets as $widget) {
                                              echo '<h1>' . $widget->getTitle() . '</h1>';
                                              echo $widget->getHtml();
                                            }
                                          ?>



                        </div>

                <!--End content-wrap-->
                </div>

                <!-- Footer -->
                <div id="footer">

                        <p>
                        &copy; Copyright <?php echo date('Y', time()); ?>
        <a href="http://www.bigace.de">BIGACE CMS</a>.    &nbsp;
                        Template by <a href="http://www.styleshout.com/">styleshout</a>

                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


                        </p>

                </div>

<!-- END Wrap -->
</div>

</body>
</html>