<?php 
/**
 * Widgets: sidebar
 */
 

$hiddenMenuID = Bigace_Config::get("marketplace", "hidden.menu");
$hiddenMenu = null;
if ($hiddenMenuID !== null) {
    $hiddenMenu = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, $hiddenMenuID, $this->MENU->getLanguageID());
}
 
$this->t()->load('bigace');
$topLevel = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, _BIGACE_TOP_LEVEL, $this->MENU->getLanguageID());
if($topLevel === null)
    $topLevel = Bigace_Item_Basic::get(_BIGACE_ITEM_MENU, _BIGACE_TOP_LEVEL);
$allLinks = $this->tplLinks($this->MENU, $this->USER);
$layout = $this->directory().'marketplace/';


?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<?php echo $this->headStyle(); ?>
<?php echo $this->headLink(); ?>

<?php echo $this->headMeta(); ?>

<?php echo $this->metatags($this->MENU); ?>

<?php echo $this->headScript(); ?>

<link rel="stylesheet" href="<?php echo $layout; ?>images/MarketPlace.css" type="text/css" />

<title>Marketplace</title>

</head>

<body>

<!-- wrap starts here -->
<div id="wrap">

	<!--header -->
	<div id="header">			
				
		<div id="header-links">
		<p>
			<a href="index.html">Home</a> | 
			<a href="index.html">Contact</a> | 
			<a href="index.html">Site Map</a>			
		</p>		
		</div>		
		
	<!--header ends-->					
	</div>
		
	<div id="header-photo">
	
		<h1 id="logo-text"><a href="<?php echo $this->link($this->topLevel);?>" title=""><?php echo $this->sitename();?></a></h1>		
		<h2 id="slogan">put your site slogan here...</h2>	
			
	</div>		
			
	<!-- navigation starts-->	
	<div  id="nav">
		<ul>
			<?php 
            echo '<li><a href="'.$this->link($topLevel).'"';
            if($this->MENU->getID() == 
                $topLevel->getID())
                echo ' class="current"';
            echo '>'.$topLevel->getName().'</a></li>';

            echo $this->menu(
                $topLevel, 
                array(
                    'prefix' => '<li>', 
                    'suffix' => '</li>', 
                    'selected' => 'current', 
                    'select' => $this->MENU, 
                    
                )
            );

        ?>
		</ul>
	<!-- navigation ends-->	
	</div>					
			
	<!-- content-wrap starts -->
	<div id="content-wrap" class="two-col"  >	
	
		<div id="sidebar">
			
			<h1>Search Box</h1>	
			<form action="<?php echo $allLinks['search']; ?>" method="post" class="searchform">
				<p>
				<input name="search" class="textbox" type="text" />
				<input type="hidden" name="language" value="<?php echo $this->MENU->getLanguageID(); ?>" />
  				<input name="searchsubmit" class="button" value="<?php echo $this->t('search_button'); ?>" type="submit" />
				</p>			
			</form>	
					
			<h1>Sidebar Menu</h1>
			<ul class="sidemenu">				
				<li><a href="index.html">Home</a></li>
				<li><a href="#TemplateInfo">Template Info</a></li>
				<li><a href="#SampleTags">Sample Tags</a></li>
				<li><a href="http://www.styleshout.com/">More Free Templates</a></li>	
				<li><a href="http://www.dreamtemplate.com" title="Web Templates">Web Templates</a></li>
			</ul>	
				
			<h1>Links</h1>
			<ul class="sidemenu">
				<?php 
              $widgets = $this->widgets($this->MENU);
              foreach($widgets as $widget) {
                echo '<li>' . $widget->getTitle() . '</li>';
                echo $widget->getHtml();
              }
            ?>
			</ul>
			
			<h1>Sponsors</h1>
			<ul class="sidemenu">
                <li><a href="http://www.dreamtemplate.com" title="Website Templates">DreamTemplate</a></li>
				<li><a href="http://www.themelayouts.com" title="WordPress Themes">ThemeLayouts</a></li>
				<li><a href="http://www.imhosted.com" title="Website Hosting">ImHosted.com</a></li>
				<li><a href="http://www.dreamstock.com" title="Stock Photos">DreamStock</a></li>
				<li><a href="http://www.evrsoft.com" title="Website Builder">Evrsoft</a></li>
                <li><a href="http://www.webhostingwp.com" title="Web Hosting">Web Hosting</a></li>
			</ul>
			
			<h1>Wise Words</h1>
			<p>&quot;We are what we repeatedly do. Excellence, then, 
			is not an act, but a habit.&quot; </p>
					
			<p class="align-right">- Aristotle</p>
					
		<!-- sidebar ends -->		
		</div>
		
		<div id="main">
				
			<?php
                echo $this->content();
                ?>	
			
		</div>
		
	<!-- content-wrap ends-->	
	</div>
		
	<!-- footer starts -->			
	<div id="footer-wrap"><div id="footer">				
			
            <p>
			&copy; Copyright <?php echo date('Y', time()); ?>
        <?php echo Bigace_Config::get("community", "copyright.holder", "BIGACE CMS"); ?>.

            &nbsp;&nbsp;&nbsp;&nbsp;

			Template by <a href="http://www.styleshout.com/">styleshout</a> 

   		    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

			<?php 
            echo '<a href="'.$this->link($topLevel).'">'.$topLevel->getName().'</a>';
            
		    if ($hiddenMenu !== null) {
		        echo $this->menu(
                    $hiddenMenu, 
                    array(
                        'prefix' => ' | ', 
                        'suffix' => '',                                        
                    )
                );
	   	    } 
   	    ?>
			</p>
			
	</div></div>
	<!-- footer ends-->	
	
<!-- wrap ends here -->
</div>

</body>
</html>
